import Router from '@koa/router'
import * as ctrl from '../controllers/auth'

// Public routes (no auth required)
export const authPublicRoutes = new Router()
authPublicRoutes.get('/api/auth/status', ctrl.authStatus)
authPublicRoutes.post('/api/auth/login', ctrl.login)
authPublicRoutes.get('/api/auth/feishu/login', ctrl.feishuLogin)
authPublicRoutes.get('/api/auth/feishu/callback', ctrl.feishuCallback)
authPublicRoutes.post('/api/auth/feishu/logout', ctrl.feishuLogout)
authPublicRoutes.post('/api/auth/logout', ctrl.logout)

// Protected routes (auth required)
export const authProtectedRoutes = new Router()
authProtectedRoutes.post('/api/auth/setup', ctrl.setupPassword)
authProtectedRoutes.post('/api/auth/change-password', ctrl.changePassword)
authProtectedRoutes.post('/api/auth/change-username', ctrl.changeUsername)
authProtectedRoutes.delete('/api/auth/password', ctrl.removePassword)
authProtectedRoutes.get('/api/auth/me', ctrl.currentUser)
authProtectedRoutes.get('/api/auth/feishu/uat/status', ctrl.feishuUatStatus)
authProtectedRoutes.post('/api/auth/feishu/uat/start', ctrl.feishuUatStart)
authProtectedRoutes.get('/api/auth/feishu/uat/sessions/:sessionId', ctrl.feishuUatPoll)
authProtectedRoutes.delete('/api/auth/feishu/uat/sessions/:sessionId', ctrl.feishuUatCancel)
authProtectedRoutes.get('/api/auth/locked-ips', ctrl.listLockedIps)
authProtectedRoutes.delete('/api/auth/locked-ips', ctrl.unlockIpHandler)
